name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  tests:
    name: "Tests on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: ["10", "12", "14"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lint
      - run: yarn test --coverage

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - tests

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 10
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - run: npx auto-dist-tag@1 --write

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
